# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bd89da1cb8d7b0a6a0e4693d308f409ebc0b072606b549c6d441ed95f3b703c0c4c7306acd5e6caf63ef942c13181cd823bbf9e183380fc162a9c8f113781dad

test:
  secret_key_base: 16f7afe3da88d9030afaf8c81a2c5b5f46ae2a3303554eb43ebee6c4b348b2024ed0e1c9eea47fa82fff7203a9b2aff7eca9f416405f3f6bc516c9206b790b54

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
